<?php

namespace App\Services;

use App\Models\Brand;
use App\Models\Talent;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

/**
 * Single source of truth for creating the three login entities. Used by BOTH
 * the public self-registration (talent/brand only — admin self-signup is
 * forbidden, ADR-I) and the admin console (all three). Each create is
 * transactional; the caller owns auth/audit side effects.
 *
 * New self-serve accounts start UNPUBLISHED in their first lifecycle state
 * (talent → draft, brand → registered) so they land in the moderation/
 * onboarding funnel rather than going live unreviewed.
 */
class AccountCreationService extends Service
{
    /**
     * Create a talent account. `name` seeds the public display name; the slug
     * is auto-generated by the model. Password is hashed by the model cast.
     *
     * @param  array<string, mixed>  $data  name, email, password
     */
    public function createTalent(array $data): Talent
    {
        return $this->runInTransaction(fn (): Talent => Talent::create([
            'display_name' => $data['name'],
            'email' => $data['email'],
            'password' => $data['password'],
            'booking_type' => 'email',
            'booking_value' => $data['email'],
            'is_published' => false,
            'status' => 'draft',
            'is_active' => true,
        ]), ['email' => $data['email'] ?? null]);
    }

    /**
     * Create a brand account. `name` is the brand name; the slug is
     * auto-generated by the model.
     *
     * @param  array<string, mixed>  $data  name, email, password
     */
    public function createBrand(array $data): Brand
    {
        return $this->runInTransaction(fn (): Brand => Brand::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => Hash::make($data['password']),
            'is_published' => false,
            'is_complete' => false,
            'is_verified' => false,
            'status' => 'registered',
            'is_active' => true,
        ]), ['email' => $data['email'] ?? null]);
    }

    /**
     * Create an admin (User) account with optional admin-guard roles. Only ever
     * called from the admin console (there is no admin self-signup).
     *
     * @param  array<string, mixed>  $data  name, email, password, locale?, roles?
     */
    public function createAdmin(array $data): User
    {
        return $this->runInTransaction(function () use ($data): User {
            $user = User::create([
                'name' => $data['name'],
                'email' => $data['email'],
                'password' => $data['password'],
                'locale' => $data['locale'] ?? 'en',
                'is_active' => true,
            ]);
            $user->syncRoles($data['roles'] ?? []);

            return $user;
        }, ['email' => $data['email'] ?? null]);
    }
}
