<?php

namespace App\Http\Controllers\Api\V1\Auth;

use App\Http\Requests\Api\V1\Auth\RegisterTalentRequest;
use App\Http\Resources\Api\V1\TalentResource;
use App\Models\Talent;
use Illuminate\Auth\Events\Registered;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * @group Talent authentication
 *
 * Token auth for the `talent` guard: public sign-up plus the shared
 * login/logout/refresh/me flow. Issued tokens carry the `talent` ability.
 */
class TalentAuthController extends AbstractAuthController
{
    protected function guard(): string
    {
        return 'talent';
    }

    protected function model(): string
    {
        return Talent::class;
    }

    protected function resource(Model $entity): JsonResource
    {
        return new TalentResource($entity->loadMissing('talentTypes'));
    }

    /**
     * Register a talent
     *
     * Create a new talent account and return an ability-scoped token. The
     * profile starts unpublished; the public slug is generated by the model.
     *
     * @unauthenticated
     *
     * @response 201 scenario="Created" {"success":true,"data":{"token":"1|xxxx","token_type":"Bearer","abilities":["talent"],"talent":{"id":1,"slug":"amgad-emad-ab12cd","display_name":"Amgad Emad"}},"message":null,"errors":null,"meta":null}
     */
    public function register(RegisterTalentRequest $request): JsonResponse
    {
        $talent = Talent::create([
            'display_name' => $request->validated('display_name'),
            'email' => $request->validated('email'),
            'password' => $request->validated('password'),
        ]);

        event(new Registered($talent));

        return $this->respondWithToken($talent, $request->deviceName(), 201);
    }
}
